// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DynamicForm: typeof import('./components/dynamic/DynamicForm.vue')['default'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    Show: typeof import('./components/Show.vue')['default'];
  }
}

export {};
